SW-318.: add --port-mask and --baudrate option
TimothyClaeys/openvisualizer pull request #1
Opened 2020-05-06 09:43 UTC by fjmolinas

This PR adds --port-mask and --baudrate option.

2020-05-11 08:25 UTC, fjmolinas commented
@TimothyClaeys Rebased!

2020-05-11 16:09 UTC, TimothyClaeys requested changes
Left some remarks, let me know if something is unclear

2020-05-11 16:09 UTC, TimothyClaeys commented on openvisualizer/main.py
> +        help='List of baudrates to probe for, e.g \'115200 500000\''
if I tried to use the option as follows:
`openv-server --baudrate=115200 500000`
or 
`openv-server --baudrate 115200 500000`
it fails.

I think you should change this to:
`
parser.add_argument(
        '--baudrate',
        dest='baudrate',
        type=int,
        default=[115200],
        action='store',
        nargs='+',
        help='List of baudrates to probe for, e.g \'115200 500000\''
    )
`

2020-05-11 16:09 UTC, TimothyClaeys commented on openvisualizer/main.py
> +        options.append('Baudrates to probe      = {0}'.format(args.baudrate))
can you change this to a small letter, just for consistency 
Baudrates --> baudrates

2020-05-11 16:09 UTC, TimothyClaeys commented on openvisualizer/main.py
>          options.append('seial port mask         = {0}'.format(args.port_mask))
fix typo: seial --> serial

2020-05-11 16:09 UTC, TimothyClaeys commented on openvisualizer/motehandler/moteprobe/moteprobe.py
> +                    log.debug("Probing port {} at baud {}".format(port, baud))
fix: change "baud" to "baudrate"

2020-05-11 16:09 UTC, TimothyClaeys commented on openvisualizer/motehandler/moteprobe/moteprobe.py
> +def find_serial_ports(is_iot_motes=False, port_mask=None, baudrate=[115200]):
the argument parser makes sure the variable "baudrate" already has the value [115200], so default value here is unnecessary?
Change to:
def find_serial_ports(baudrate, is_iot_motes=False, port_mask=None):

2020-05-11 16:09 UTC, TimothyClaeys commented on openvisualizer/main.py
> +
this function is not necessary.
see https://stackoverflow.com/questions/15753701/how-can-i-pass-a-list-as-a-command-line-argument-with-argparse

2020-05-11 16:09 UTC, TimothyClaeys commented on openvisualizer/main.py
> +    parser.add_argument(
Don't use "list_from_string", something like this should work I think:    

parser.add_argument(
        '--port-mask',
        dest='port_mask',
        type=str,
        action='store',
        nargs='+',
        help='List of baudrates to probe for, e.g \'115200 500000\''
    )

2020-05-11 16:09 UTC, TimothyClaeys commented on openvisualizer/motehandler/moteprobe/moteprobe.py
> +    if port_mask == None:
if port_mask is None

2020-05-12 07:05 UTC, fjmolinas commented
@TimothyClaeys I think I addressed your change requests, let me know if there is anything remaining!

2020-05-14 08:03 UTC, fjmolinas commented
In my last push I believe I fixed the issues you mentioned offline. Testing procedure:

- `openv-server --baudrate 9600 115200 500000`

```
09:56:07 [OpenVisualizerServer:VERBOSE] Loading logging configuration: config/logging.conf
09:56:07 [OpenVisualizerServer:INFO] Initializing OV Server with options:
                - use page zero           = False
                - use VCD logger          = False
                - baudrates to probe      = ['9600', '115200', '500000']
09:56:09 [MoteProbe:WARNING] MoteProbe@/dev/ttyUSB1: invalid serial frame: (100B) 7e-9e-c2-ff-ff-ff-ff-ff-ff-1c-1e-9e-ff-ff-ff-ff-ff-ff-ff-ff-ff-c0-c0-e0-e0-3c-3c-1c-1e-ff-ff-3d-ff-ff-ff-ff-ff-ff-ff-e0-fc-ff-ff-ff-ff-ff-ff-fc-fc-f8-ff-ff-ff-ff-ff-ff-ff-3d-ff-ff-fc-1e-c0-ff-ff-ff-ff-ff-ff-ff-ff-0f-c0-c0-f8-ff-ff-ff-ff-ff-c0-c0-e0-e0-c0-c0-e0-e0-ff-ff-3d-ff-ff-ff-ff-ff-ff-e0-fc-7e wrong CRC
09:56:16 [MoteProbe:SUCCESS] discovered following serial-port(s): ['/dev/ttyUSB1@115200']
09:56:16 [OpenVisualizerServer:INFO] Extracting firmware definitions.
09:56:16 [Utils:VERBOSE] Extracting firmware component names
09:56:16 [Utils:VERBOSE] Generating firmware log descriptions.
09:56:16 [Utils:VERBOSE] Extracting 6top return codes.
09:56:16 [Utils:VERBOSE] Extracting 6top states.
09:56:16 [OpenVisualizerServer:INFO] Starting RPC server
09:56:16 [RPL:INFO] registering DAGroot 00-12-4b-00-14-b5-b5-af
```

- `openv-server --baudrate 9600 500000 115200`

```
09:57:39 [OpenVisualizerServer:VERBOSE] Loading logging configuration: config/logging.conf
09:57:39 [OpenVisualizerServer:INFO] Initializing OV Server with options:
                - use page zero           = False
                - use VCD logger          = False
                - baudrates to probe      = ['9600', '500000', '115200']
09:57:43 [MoteProbe:WARNING] MoteProbe@/dev/ttyUSB1: invalid serial frame: (2157B) 7e-ff-ff-ff-3d-fc-ff-ff-ff-ff-fc-9e-1e-ff-ff-ff-ff-ff-ff-ff-ff-ff-fe-cf-ff-ff-ff-ff-ff-3c-fa-f6-ff-e0-e0-e0-ff-ff-ff-ff-ff-ff-ff-ff-fc-e0-f0-f0-f0-ff-ff-ff-ff-ff-ff-ff-ff-e0-e0-f0-f0-ff-ff-ff-ff-e0-ff-ff-ff-fc-9e-1e-ff-ff-ff-ff-ff-ff-ff-ff-ff-ff-fe-cf-ff-ff-ff-ff-ff-ff-ff-3d-fa-f6-c0-c0-c0-fe-ff-ff-ff-ff-ff-ff-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 [...]

2020-05-14 09:46 UTC, merged

2020-05-14 10:20 UTC, fjmolinas commented
Thanks for the review!